{
  return "try {\n} catch (Error err) {\n\n}";
}
